# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:SkipInvalidConfigurations=true /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: OctopusPack@4
  inputs:
    PackageId: 'RandomQuotesADO'
    PackageFormat: 'NuPkg'
    PackageVersion: '1.0.$(Build.BuildId)'
    SourcePath: '$(Build.SourcesDirectory)\RandomQuotes'

- task: OctopusPack@4
  inputs:
    PackageId: 'RandomQuotesADOzip'
    PackageFormat: 'Zip'
    PackageVersion: '1.0.$(Build.BuildId)'
    SourcePath: '$(Build.SourcesDirectory)\RandomQuotes'

- task: OctopusPush@7
  inputs:
    OctoConnectedServiceName: 'octopus'
    Space: 'maryia'
    Packages: |
      RandomQuotesADO.1.0.$(Build.BuildId).nupkg
      RandomQuotesADOzip.1.0.$(Build.BuildId).zip
    Replace: 'true'

- task: OctopusBuildInformation@7
  inputs:
    OctoConnectedServiceName: 'octopus'
    Space: 'maryia'
    PackageIds: 'RandomQuotesADO'
    PackageVersion: '1.0.$(Build.BuildId)'
    Replace: 'true'